# Generated by Django 6.0.5 on 2026-06-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('teacher', 'teacher'), ('assistant', 'assistant'), ('parent', 'parent'), ('student', 'student')], default='student', max_length=50),
        ),
    ]
