# Generated by Django 5.2.4 on 2026-09-29 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('answer_type', models.CharField(choices=[('choice', 'Choice'), ('text', 'Text')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='homework',
            name='file',
        ),
        migrations.AddField(
            model_name='homework',
            name='submission_type',
            field=models.CharField(blank=True, choices=[('file', 'File'), ('image', 'Image')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='submissions/images/'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/files/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.questiontitle'),
        ),
    ]
