# Generated by Django 5.2.4 on 2026-09-29 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_questiontitle_remove_homework_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='text_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.choice'),
        ),
    ]
